install:
  #- sudo apt-get -y update
  #- sudo cabal install shellcheck
  apt:
    sources: 
    - debian-sid  #grab shellcheck from debian repo
    packages: 
    - shellcheck

script:
  - more /etc/issue
  # Check fi-backup.sh syntax
  - shellcheck backupinator.sh

