#install:
  #- sudo apt-get -y update
  #- sudo cabal install shellcheck

# Use container-based infrastructure for quicker build start-up
sudo: false

addons: 
  apt:
    sources: 
    - debian-sid  #grab shellcheck from debian repo
    packages: 
    - shellcheck

script:
  - more /etc/issue
  # Check fi-backup.sh syntax
  - shellcheck backupinator.sh

